.TH "valentineweek.make_couples" 3 "Sun Feb 26 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
valentineweek.make_couples
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBmake\fP (int b_no, int g_no)  throws IOException     "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgirl\fP [] \fBcommitgirls\fP = new \fBgirl\fP[1000]"
.br
.ti -1c
.RI "\fBboy\fP [] \fBcommitboys\fP = new \fBboy\fP[10000]"
.br
.ti -1c
.RI "int \fBcount\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file make_couples\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
