.TH "valentineweek.read_data" 3 "Sun Feb 26 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
valentineweek.read_data
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 13 of file read_data\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
