.TH "valentineweek.boy" 3 "Sun Feb 26 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
valentineweek.boy
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBboy\fP (String name, int attract_rating, double maintenance_budget, int intel_level, int min_attract, String commit_type)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "String \fBname\fP"
.br
.ti -1c
.RI "int \fBattract_rating\fP"
.br
.ti -1c
.RI "double \fBmaintenance_budget\fP"
.br
.ti -1c
.RI "int \fBintel_level\fP"
.br
.ti -1c
.RI "int \fBmin_attract\fP"
.br
.ti -1c
.RI "char \fBcommit\fP"
.br
.ti -1c
.RI "String \fBcommit_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Debadutta Godnaik 
.RE
.PP

.PP
Definition at line 12 of file boy\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
