.TH "valentineweek.ValentineWeek" 3 "Sun Feb 26 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
valentineweek.ValentineWeek
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws IOException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file ValentineWeek\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void valentineweek\&.ValentineWeek\&.main (String [] args) throws IOException\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIargs\fP the command line arguments 
.RE
.PP

.PP
Definition at line 18 of file ValentineWeek\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
