.TH "valentineweek.logging_util" 3 "Sun Feb 26 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
valentineweek.logging_util
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (String event, String descp)  throws IOException      "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file logging_util\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
